#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - git

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker azureuser
  - mkdir -p /home/azureuser/app
  - chown azureuser:azureuser /home/azureuser/app

write_files:
  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        }
      }
